-- Script SQL d'insertion des 450 micro-leçons
-- Base de données: ScientificApp
-- Table: microlessons


CREATE TABLE IF NOT EXISTS microlessons (
    id VARCHAR(10) PRIMARY KEY,
    level VARCHAR(20) NOT NULL,
    subject VARCHAR(50) NOT NULL,
    chapter VARCHAR(100) NOT NULL,
    title VARCHAR(200) NOT NULL,
    duration_min INT NOT NULL,
    objectives JSON NOT NULL,
    prerequisites JSON NOT NULL,
    content_types JSON NOT NULL,
    difficulty INT NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
    xp_reward INT NOT NULL,
    tags JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_level (level),
    INDEX idx_subject (subject),
    INDEX idx_chapter (chapter),
    INDEX idx_difficulty (difficulty)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- Insertion des micro-leçons

INSERT INTO microlessons (id, level, subject, chapter, title, duration_min, objectives, prerequisites, content_types, difficulty, xp_reward, tags) VALUES

('P1-01', 'Première', 'Physique', 'Mécanique', 'Vecteur vitesse', 8, '["Définir vecteur vitesse", "Calculer v⃗", "Direction et sens"]', '["Vitesse Seconde", "Vecteurs"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["vecteur", "vitesse"]'),
('P1-02', 'Première', 'Physique', 'Mécanique', 'Vecteur accélération', 8, '["Définir vecteur accélération", "Calculer a⃗", "Relation avec variation vitesse"]', '["Vecteur vitesse"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["vecteur", "accélération"]'),
('P1-03', 'Première', 'Physique', 'Mécanique', 'Deuxième loi de Newton', 9, '["Énoncer F⃗=ma⃗", "Appliquer la loi", "Résoudre des problèmes"]', '["Forces", "Accélération"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["deuxième", "loi", "de"]'),
('P1-04', 'Première', 'Physique', 'Mécanique', 'Chute libre', 8, '["Étudier la chute libre", "Équations du mouvement", "Applications"]', '["Newton", "Pesanteur"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["chute", "libre"]'),
('P1-05', 'Première', 'Physique', 'Mécanique', 'Mouvement circulaire uniforme', 8, '["Caractériser MCU", "Vitesse angulaire", "Accélération centripète"]', '["Vitesse", "Vecteurs"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["mouvement", "circulaire", "uniforme"]'),
('P1-06', 'Première', 'Physique', 'Mécanique', 'Mouvement parabolique (projectile)', 9, '["Étudier le tir de projectile", "Équations paramétriques", "Portée et hauteur max"]', '["Chute libre", "Vecteurs"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["mouvement", "parabolique", "(projectile)"]'),
('P1-07', 'Première', 'Physique', 'Mécanique', 'Forces et mouvements', 8, '["Relier force et mouvement", "Principe fondamental", "Applications variées"]', '["Newton"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["forces", "et", "mouvements"]'),
('P1-08', 'Première', 'Physique', 'Mécanique', 'Énergie cinétique', 7, '["Définir Ec=½mv²", "Calculer l'énergie cinétique", "Théorème de l'énergie cinétique"]', '["Vitesse", "Énergie"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["énergie", "cinétique"]'),
('P1-09', 'Première', 'Physique', 'Mécanique', 'Énergie potentielle de pesanteur', 7, '["Définir Ep=mgh", "Calculer Ep", "Référence d'altitude"]', '["Poids", "Énergie"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["énergie", "potentielle", "de"]'),
('P1-10', 'Première', 'Physique', 'Mécanique', 'Travail d'une force', 8, '["Définir W=F⃗·d⃗", "Calculer un travail", "Travail moteur/résistant"]', '["Forces", "Vecteurs"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["travail", "d'une", "force"]'),
('P1-11', 'Première', 'Physique', 'Mécanique', 'Puissance mécanique', 7, '["Définir P=W/Δt", "Calculer une puissance", "Applications"]', '["Travail"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["puissance", "mécanique"]'),
('P1-12', 'Première', 'Physique', 'Mécanique', 'Conservation de l'énergie mécanique', 8, '["Em=Ec+Ep=constante", "Appliquer le principe", "Situations sans frottements"]', '["Ec", "Ep"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["conservation", "de", "l'énergie"]'),
('P1-13', 'Première', 'Physique', 'Ondes', 'Ondes mécaniques progressives', 8, '["Définir onde progressive", "Célérité", "Propagation"]', '["Ondes Seconde"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["ondes", "mécaniques", "progressives"]'),
('P1-14', 'Première', 'Physique', 'Ondes', 'Ondes sinusoïdales', 8, '["Caractériser onde sinusoïdale", "Période, fréquence", "Longueur d'onde"]', '["Ondes progressives"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["ondes", "sinusoïdales"]'),
('P1-15', 'Première', 'Physique', 'Ondes', 'Période, fréquence, longueur d'onde', 7, '["Relations T, f, λ", "Formule v=λf", "Applications"]', '["Ondes sinusoïdales"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["période,", "fréquence,", "longueur"]'),
('P1-16', 'Première', 'Physique', 'Ondes', 'Célérité d'une onde', 7, '["Mesurer la célérité", "Facteurs influençant", "Applications"]', '["Ondes"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["célérité", "d'une", "onde"]'),
('P1-17', 'Première', 'Physique', 'Ondes', 'Diffraction des ondes', 8, '["Observer la diffraction", "Relation θ≈λ/a", "Applications"]', '["Ondes"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["diffraction", "des", "ondes"]'),
('P1-18', 'Première', 'Physique', 'Ondes', 'Interférences', 8, '["Comprendre les interférences", "Constructives et destructives", "Conditions"]', '["Ondes"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["interférences"]'),
('P1-19', 'Première', 'Physique', 'Ondes', 'Effet Doppler (introduction)', 8, '["Découvrir l'effet Doppler", "Variation de fréquence", "Applications"]', '["Fréquence"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["effet", "doppler", "(introduction)"]'),
('P1-20', 'Première', 'Physique', 'Ondes', 'Ondes sonores et ultrasons', 7, '["Caractéristiques du son", "Ultrasons", "Applications médicales"]', '["Ondes Seconde"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["ondes", "sonores", "et"]'),
('P1-21', 'Première', 'Physique', 'Ondes', 'Spectre sonore', 7, '["Analyse fréquentielle", "Spectre", "Timbre"]', '["Son"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["spectre", "sonore"]'),
('P1-22', 'Première', 'Physique', 'Ondes', 'Applications des ondes', 8, '["Échographie", "Radar", "Sismologie"]', '["Ondes complètes"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["applications", "des", "ondes"]'),
('P1-23', 'Première', 'Physique', 'Électricité', 'Courant électrique', 7, '["Définir le courant", "Intensité I", "Sens du courant"]', '["Aucun"]', '["video", "animation", "quiz", "exercises"]', 1, 50, '["courant", "électrique"]'),
('P1-24', 'Première', 'Physique', 'Électricité', 'Tension et intensité', 7, '["Définir la tension U", "Mesurer U et I", "Appareils"]', '["Courant"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["tension", "et", "intensité"]'),
('P1-25', 'Première', 'Physique', 'Électricité', 'Loi d'Ohm', 7, '["U=RI", "Résistance", "Applications"]', '["Tension", "Intensité"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["loi", "d'ohm"]'),
('P1-26', 'Première', 'Physique', 'Électricité', 'Conducteurs ohmiques', 7, '["Caractéristiques", "Comportement linéaire", "Applications"]', '["Loi d'Ohm"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["conducteurs", "ohmiques"]'),
('P1-27', 'Première', 'Physique', 'Électricité', 'Circuits en série et parallèle', 8, '["Lois des circuits série", "Lois des circuits parallèle", "Calculs"]', '["Loi d'Ohm"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["circuits", "en", "série"]'),
('P1-28', 'Première', 'Physique', 'Électricité', 'Générateurs et récepteurs', 7, '["Rôle des générateurs", "Rôle des récepteurs", "f.e.m."]', '["Circuits"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["générateurs", "et", "récepteurs"]'),
('P1-29', 'Première', 'Physique', 'Électricité', 'Énergie électrique', 7, '["Calculer E=UIt", "Énergie consommée", "kWh"]', '["Tension", "Intensité"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["énergie", "électrique"]'),
('P1-30', 'Première', 'Physique', 'Électricité', 'Puissance électrique', 8, '["P=UI", "Calculs de puissance", "Applications"]', '["Énergie électrique"]', '["video", "animation", "quiz", "exercises"]', 2, 60, '["puissance", "électrique"]'),
('C1-01', 'Première', 'Chimie', 'Structure & Transformation', 'Configuration électronique', 8, '["Règles de remplissage", "Écrire config électronique", "Couches et sous-couches"]', '["Structure atome"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["configuration", "électronique"]'),
('C1-02', 'Première', 'Chimie', 'Structure & Transformation', 'Règles de remplissage', 7, '["Klechkowski", "Ordre de remplissage", "Exceptions"]', '["Config électronique"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["règles", "de", "remplissage"]'),
('C1-03', 'Première', 'Chimie', 'Structure & Transformation', 'Familles chimiques', 7, '["Identifier familles", "Propriétés", "Tableau périodique"]', '["Config électronique"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["familles", "chimiques"]'),
('C1-04', 'Première', 'Chimie', 'Structure & Transformation', 'Liaisons covalentes', 8, '["Définir liaison covalente", "Doublets liants/non-liants", "Représentation Lewis"]', '["Atomes", "Électrons"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["liaisons", "covalentes"]'),
('C1-05', 'Première', 'Chimie', 'Structure & Transformation', 'Géométrie des molécules (VSEPR)', 9, '["Modèle VSEPR", "Prévoir la géométrie", "Formes moléculaires"]', '["Liaisons covalentes"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["géométrie", "des", "molécules"]'),
('C1-06', 'Première', 'Chimie', 'Structure & Transformation', 'Électronégativité', 7, '["Définir électronégativité", "Échelle de Pauling", "Utilisation"]', '["Liaisons"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["électronégativité"]'),
('C1-07', 'Première', 'Chimie', 'Structure & Transformation', 'Polarité des liaisons', 8, '["Liaison polaire/apolaire", "Moment dipolaire", "Conséquences"]', '["Électronégativité"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["polarité", "des", "liaisons"]'),
('C1-08', 'Première', 'Chimie', 'Structure & Transformation', 'Forces intermoléculaires', 8, '["Van der Waals", "Liaisons hydrogène", "Influence propriétés"]', '["Polarité"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["forces", "intermoléculaires"]'),
('C1-09', 'Première', 'Chimie', 'Structure & Transformation', 'Transformations acide-base', 8, '["Acides et bases", "Couples acide/base", "Réactions"]', '["pH Seconde"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["transformations", "acide-base"]'),
('C1-10', 'Première', 'Chimie', 'Structure & Transformation', 'pH et pKa', 8, '["Définir pKa", "Relation pH/pKa", "Diagramme"]', '["pH"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["ph", "et", "pka"]'),
('C1-11', 'Première', 'Chimie', 'Structure & Transformation', 'Réactions d'oxydo-réduction', 9, '["Oxydant et réducteur", "Couples redox", "Réactions"]', '["Ions"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["réactions", "d'oxydo-réduction"]'),
('C1-12', 'Première', 'Chimie', 'Structure & Transformation', 'Équations redox', 8, '["Équilibrer équations redox", "Demi-équations", "Méthode"]', '["Redox"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["équations", "redox"]'),
('C1-13', 'Première', 'Chimie', 'Chimie Organique', 'Chaînes carbonées', 7, '["Atome de carbone", "Tétravalence", "Chaînes"]', '["Liaisons"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["chaînes", "carbonées"]'),
('C1-14', 'Première', 'Chimie', 'Chimie Organique', 'Formules brutes et semi-développées', 7, '["Écrire différentes formules", "Représentations", "Conventions"]', '["Chaînes carbonées"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["formules", "brutes", "et"]'),
('C1-15', 'Première', 'Chimie', 'Chimie Organique', 'Groupes caractéristiques', 8, '["Identifier groupes fonctionnels", "Alcool, aldéhyde, cétone, acide", "Propriétés"]', '["Formules"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["groupes", "caractéristiques"]'),
('C1-16', 'Première', 'Chimie', 'Chimie Organique', 'Nomenclature (alcanes)', 8, '["Règles IUPAC", "Nommer alcanes", "Ramifications"]', '["Chaînes"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["nomenclature", "(alcanes)"]'),
('C1-17', 'Première', 'Chimie', 'Chimie Organique', 'Nomenclature (alcools)', 7, '["Nommer les alcools", "Position du OH", "Règles"]', '["Alcanes", "Groupes"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["nomenclature", "(alcools)"]'),
('C1-18', 'Première', 'Chimie', 'Chimie Organique', 'Nomenclature (autres fonctions)', 8, '["Aldéhydes, cétones, acides", "Nomenclature complète", "Exercices"]', '["Nomenclature alcools"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["nomenclature", "(autres", "fonctions)"]'),
('C1-19', 'Première', 'Chimie', 'Chimie Organique', 'Isomérie de constitution', 8, '["Définir isomères", "Isomères de chaîne, position, fonction", "Exemples"]', '["Formules"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["isomérie", "de", "constitution"]'),
('C1-20', 'Première', 'Chimie', 'Chimie Organique', 'Réactivité des alcools', 8, '["Réactions des alcools", "Mécanismes simples", "Produits"]', '["Alcools"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["réactivité", "des", "alcools"]'),
('C1-21', 'Première', 'Chimie', 'Chimie Organique', 'Réactions d'oxydation', 9, '["Oxydation alcools", "Oxydants", "Aldéhydes/cétones/acides"]', '["Réactivité alcools"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["réactions", "d'oxydation"]'),
('C1-22', 'Première', 'Chimie', 'Chimie Organique', 'Réactions d'estérification', 9, '["Formation d'esters", "Acide + alcool", "Équilibre"]', '["Alcools", "Acides"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["réactions", "d'estérification"]'),
('C1-23', 'Première', 'Chimie', 'Chimie Organique', 'Synthèse organique', 9, '["Planifier une synthèse", "Étapes", "Rendement"]', '["Réactions organiques"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["synthèse", "organique"]'),
('C1-24', 'Première', 'Chimie', 'Chimie Organique', 'Extraction et purification', 8, '["Techniques d'extraction", "Purification", "Chromatographie"]', '["Synthèse"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["extraction", "et", "purification"]'),
('C1-25', 'Première', 'Chimie', 'Chimie Organique', 'Protocoles expérimentaux', 8, '["Suivre un protocole", "Sécurité", "Analyse"]', '["Synthèse"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["protocoles", "expérimentaux"]'),
('PT-01', 'Terminale', 'Physique', 'Mécanique Avancée', 'Mouvement dans un champ de pesanteur', 9, '["Étudier mouvement parabolique", "Avec frottements", "Applications"]', '["Mécanique Première"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["mouvement", "dans", "un"]'),
('PT-02', 'Terminale', 'Physique', 'Mécanique Avancée', 'Mouvement des planètes', 9, '["Lois de Kepler", "Orbites elliptiques", "Applications"]', '["Gravitation"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["mouvement", "des", "planètes"]'),
('PT-03', 'Terminale', 'Physique', 'Mécanique Avancée', 'Lois de Kepler', 9, '["Trois lois de Kepler", "Démonstrations", "Conséquences"]', '["Mouvement planètes"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["lois", "de", "kepler"]'),
('PT-04', 'Terminale', 'Physique', 'Mécanique Avancée', 'Satellites et orbites', 8, '["Satellites géostationnaires", "Vitesse orbitale", "Période"]', '["Kepler"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["satellites", "et", "orbites"]'),
('PT-05', 'Terminale', 'Physique', 'Mécanique Avancée', 'Énergie mécanique d'un satellite', 9, '["Énergie potentielle gravitationnelle", "Énergie totale", "Vitesse de libération"]', '["Satellites"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["énergie", "mécanique", "d'un"]'),
('PT-06', 'Terminale', 'Physique', 'Mécanique Avancée', 'Mouvement dans un champ électrique', 9, '["Force électrique", "Accélération", "Trajectoire"]', '["Newton"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["mouvement", "dans", "un"]'),
('PT-07', 'Terminale', 'Physique', 'Mécanique Avancée', 'Mouvement dans un champ magnétique', 9, '["Force de Lorentz", "Trajectoire circulaire", "Applications"]', '["Champ électrique"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["mouvement", "dans", "un"]'),
('PT-08', 'Terminale', 'Physique', 'Mécanique Avancée', 'Force de Lorentz', 8, '["F⃗=q(E⃗+v⃗∧B⃗)", "Composantes", "Calculs"]', '["Champs"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["force", "de", "lorentz"]'),
('PT-09', 'Terminale', 'Physique', 'Mécanique Avancée', 'Applications (cyclotron, spectrographe)', 9, '["Cyclotron", "Spectrographe de masse", "Principe"]', '["Lorentz"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["applications", "(cyclotron,", "spectrographe)"]'),
('PT-10', 'Terminale', 'Physique', 'Mécanique Avancée', 'Dynamique relativiste (introduction)', 9, '["Limites mécanique classique", "Effets relativistes", "E=mc²"]', '["Mécanique avancée"]', '["video", "animation", "quiz", "exercises"]', 4, 100, '["dynamique", "relativiste", "(introduction)"]'),
('PT-11', 'Terminale', 'Physique', 'Ondes & Signaux', 'Ondes progressives périodiques', 8, '["Caractériser onde périodique", "Double périodicité", "Applications"]', '["Ondes Première"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["ondes", "progressives", "périodiques"]'),
('PT-12', 'Terminale', 'Physique', 'Ondes & Signaux', 'Analyse spectrale', 8, '["Spectroscopie", "Raies d'émission/absorption", "Identification"]', '["Spectres"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["analyse", "spectrale"]'),
('PT-13', 'Terminale', 'Physique', 'Ondes & Signaux', 'Effet Doppler (approfondissement)', 9, '["Formules Doppler", "Cas général", "Applications astronomiques"]', '["Doppler Première"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["effet", "doppler", "(approfondissement)"]'),
('PT-14', 'Terminale', 'Physique', 'Ondes & Signaux', 'Lunette astronomique', 8, '["Principe de la lunette", "Grossissement", "Utilisation"]', '["Optique"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["lunette", "astronomique"]'),
('PT-15', 'Terminale', 'Physique', 'Ondes & Signaux', 'Télescope', 8, '["Principe du télescope", "Avantages", "Types"]', '["Lunette"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["télescope"]'),
('PT-16', 'Terminale', 'Physique', 'Ondes & Signaux', 'Diffraction par une fente', 9, '["Figure de diffraction", "Écart angulaire θ=λ/a", "Observations"]', '["Diffraction Première"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["diffraction", "par", "une"]'),
('PT-17', 'Terminale', 'Physique', 'Ondes & Signaux', 'Diffraction par un obstacle circulaire', 8, '["Tache d'Airy", "Rayon angulaire", "Applications"]', '["Diffraction fente"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["diffraction", "par", "un"]'),
('PT-18', 'Terminale', 'Physique', 'Ondes & Signaux', 'Critère de Rayleigh', 8, '["Pouvoir séparateur", "Résolution optique", "Applications"]', '["Diffraction"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["critère", "de", "rayleigh"]'),
('PT-19', 'Terminale', 'Physique', 'Ondes & Signaux', 'Interférences à deux ondes', 9, '["Dispositif des fentes d'Young", "Franges d'interférence", "Calculs"]', '["Interférences Première"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["interférences", "à", "deux"]'),
('PT-20', 'Terminale', 'Physique', 'Ondes & Signaux', 'Applications en physique moderne', 9, '["Interférométrie", "Holographie", "Techniques modernes"]', '["Interférences"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["applications", "en", "physique"]'),
('PT-21', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Dipôles RC', 9, '["Circuit RC", "Constante de temps τ=RC", "Équation différentielle"]', '["Circuits Première"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["dipôles", "rc"]'),
('PT-22', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Charge et décharge d'un condensateur', 9, '["Étudier charge/décharge", "Courbes", "Applications"]', '["RC"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["charge", "et", "décharge"]'),
('PT-23', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Énergie stockée dans un condensateur', 8, '["E=½CU²", "Calculs", "Applications"]', '["Condensateur"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["énergie", "stockée", "dans"]'),
('PT-24', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Dipôles RL', 9, '["Circuit RL", "Constante de temps τ=L/R", "Équation différentielle"]', '["RC"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["dipôles", "rl"]'),
('PT-25', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Auto-induction', 8, '["Phénomène d'induction", "Bobine", "f.e.m. induite"]', '["RL"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["auto-induction"]'),
('PT-26', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Transferts énergétiques en électricité', 8, '["Bilan énergétique", "Rendement", "Pertes"]', '["Énergie électrique"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["transferts", "énergétiques", "en"]'),
('PT-27', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Oscillations électriques (RLC)', 10, '["Circuit RLC", "Oscillations", "Amortissement"]', '["RC", "RL"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["oscillations", "électriques", "(rlc)"]'),
('PT-28', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Résonance', 9, '["Résonance d'un circuit", "Fréquence propre", "Applications"]', '["RLC"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["résonance"]'),
('PT-29', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Champs magnétiques', 8, '["Créer un champ B⃗", "Bobine, aimant", "Mesure"]', '["Magnétisme"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["champs", "magnétiques"]'),
('PT-30', 'Terminale', 'Physique', 'Électricité & Électromagnétisme', 'Induction électromagnétique', 9, '["Loi de Faraday", "Loi de Lenz", "Applications"]', '["Champs magnétiques"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["induction", "électromagnétique"]'),
('CT-01', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Vitesse de réaction', 8, '["Définir vitesse réaction", "Facteurs cinétiques", "Mesure"]', '["Réactions chimiques"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["vitesse", "de", "réaction"]'),
('CT-02', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Facteurs cinétiques (température)', 8, '["Influence température", "Loi d'Arrhenius", "Applications"]', '["Vitesse réaction"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["facteurs", "cinétiques", "(température)"]'),
('CT-03', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Facteurs cinétiques (concentration)', 8, '["Influence concentration", "Ordre de réaction", "Loi de vitesse"]', '["Vitesse réaction"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["facteurs", "cinétiques", "(concentration)"]'),
('CT-04', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Catalyse', 8, '["Rôle du catalyseur", "Types de catalyse", "Applications"]', '["Cinétique"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["catalyse"]'),
('CT-05', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Mécanismes réactionnels', 9, '["Étapes élémentaires", "Intermédiaires", "Étape cinétiquement déterminante"]', '["Vitesse", "Catalyse"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["mécanismes", "réactionnels"]'),
('CT-06', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Énergie d'activation', 8, '["Définir Ea", "Diagramme énergétique", "Influence sur vitesse"]', '["Mécanismes"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["énergie", "d'activation"]'),
('CT-07', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Loi d'Arrhenius', 9, '["k=A·exp(-Ea/RT)", "Applications", "Détermination Ea"]', '["Énergie activation"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["loi", "d'arrhenius"]'),
('CT-08', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Transformations spontanées', 8, '["Critère de spontanéité", "Entropie", "Énergie libre"]', '["Thermodynamique"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["transformations", "spontanées"]'),
('CT-09', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Transformations forcées', 8, '["Électrolyse", "Piles", "Applications"]', '["Redox"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["transformations", "forcées"]'),
('CT-10', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Premier principe de thermodynamique', 9, '["Conservation énergie", "ΔU=W+Q", "Applications"]', '["Énergie"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["premier", "principe", "de"]'),
('CT-11', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Enthalpie de réaction', 9, '["Définir ΔH", "Réaction exo/endothermique", "Calculs"]', '["Premier principe"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["enthalpie", "de", "réaction"]'),
('CT-12', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Transformations endothermiques/exothermiques', 8, '["Caractériser les transformations", "Exemples", "Diagrammes"]', '["Enthalpie"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["transformations", "endothermiques/exothermiques"]'),
('CT-13', 'Terminale', 'Chimie', 'Cinétique & Thermodynamique', 'Applications énergétiques', 9, '["Combustion", "Pile à combustible", "Rendement"]', '["Thermodynamique complète"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["applications", "énergétiques"]'),
('CT-14', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'État d'équilibre chimique', 8, '["Définir l'équilibre", "Système fermé", "Constante K"]', '["Réactions"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["état", "d'équilibre", "chimique"]'),
('CT-15', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Constante d'équilibre K', 8, '["Expression de K", "Calculs", "Unités"]', '["Équilibre"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["constante", "d'équilibre", "k"]'),
('CT-16', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Quotient de réaction Q', 8, '["Définir Q", "Comparer Q et K", "Sens d'évolution"]', '["Constante K"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["quotient", "de", "réaction"]'),
('CT-17', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Loi de Le Chatelier', 9, '["Perturbations d'un équilibre", "Déplacements", "Applications"]', '["Équilibre"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["loi", "de", "le"]'),
('CT-18', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Équilibres acide-base', 9, '["Ka et pKa", "pH solutions", "Calculs"]', '["Acide-base Première"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["équilibres", "acide-base"]'),
('CT-19', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Dosage par titrage direct', 9, '["Principe du dosage", "Point d'équivalence", "Calculs"]', '["Équilibres"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["dosage", "par", "titrage"]'),
('CT-20', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Dosage pH-métrique', 9, '["Suivi pH-métrique", "Courbe de titrage", "Exploitation"]', '["Dosage"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["dosage", "ph-métrique"]'),
('CT-21', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Dosage conductimétrique', 9, '["Suivi conductimétrique", "Courbe", "Exploitation"]', '["Dosage"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["dosage", "conductimétrique"]'),
('CT-22', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Dosage colorimétrique', 8, '["Suivi colorimétrique", "Spectrophotométrie", "Loi de Beer-Lambert"]', '["Dosage"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["dosage", "colorimétrique"]'),
('CT-23', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Indicateurs colorés', 7, '["Rôle des indicateurs", "Zone de virage", "Choix"]', '["pH", "Dosage"]', '["video", "animation", "quiz", "exercises"]', 2, 70, '["indicateurs", "colorés"]'),
('CT-24', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Dosages redox', 9, '["Titrages redox", "Équivalence", "Applications"]', '["Redox", "Dosages"]', '["video", "animation", "quiz", "exercises"]', 4, 90, '["dosages", "redox"]'),
('CT-25', 'Terminale', 'Chimie', 'Équilibres & Dosages', 'Applications analytiques', 9, '["Dosages dans l'industrie", "Analyse quantitative", "Méthodes"]', '["Tous dosages"]', '["video", "animation", "quiz", "exercises"]', 3, 80, '["applications", "analytiques"]')
;


-- Statistiques
-- Total micro-leçons: 110

-- Par niveau:
-- Première: 55 leçons
-- Terminale: 55 leçons

-- Par matière:
-- Chimie: 50 leçons
-- Physique: 60 leçons